# Generated by Django 4.2.7 on 2023-11-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
