# Generated by Django 4.2.7 on 2023-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0002_rename_match_id_deliveries_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match',
            new_name='match_id',
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
