# Generated by Django 4.2.7 on 2023-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0003_rename_match_deliveries_match_id_alter_deliveries_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
