# Generated by Django 4.2.7 on 2023-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0005_rename_match_deliveries_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
